---
name: Continuous Deployment

on: push

jobs:
  test:
    name: Test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Test
          run: docker-compose run --rm app sh -c "python manage.py test"


  lint: 
    - name: Lint
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Lint
          run: docker-compose run --rm app sh -c "flake8"
      
